# Pandas basics

In [1]:
import numpy as np
import pandas as pd

### How to create a series?

In [2]:
labels=['a','b','c']

In [3]:
mylist=[10,20,30]

In [4]:
arr=np.array(mylist)

In [5]:
arr

array([10, 20, 30])

In [6]:
d={'a': 10, 'b' : 20, 'c' : 30}

In [7]:
pd.Series(mylist)

0    10
1    20
2    30
dtype: int64

In [8]:
pd.Series(data=mylist)

0    10
1    20
2    30
dtype: int64

In [9]:
pd.Series(arr)

0    10
1    20
2    30
dtype: int64

In [10]:
pd.Series(arr,labels)

a    10
b    20
c    30
dtype: int64

In [11]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

### Series manipulations

In [12]:
ser1=pd.Series(data=[1,2,3,4], index=['USA','Ger','GB','Japan'])
ser1

USA      1
Ger      2
GB       3
Japan    4
dtype: int64

In [18]:
ser1['Japan'] # access the value using the label

4

In [19]:
ser1[3]  # access the value using the raw index

4

In [20]:
ser2=pd.Series(data=[1,2,3,4], index=['USA','Ger','Italy','Japan'])
ser2

USA      1
Ger      2
Italy    3
Japan    4
dtype: int64

In [21]:
ser1+ser2  # series addition

GB       NaN
Ger      4.0
Italy    NaN
Japan    8.0
USA      2.0
dtype: float64

### DataFrame creation

#### Series can only contain single list with index, whereas dataframe can be made of more than one series or we can say that a dataframe is a collection of series that can be used to analyse the data. DataFrame is actually stored in memory as a collection of Series. DataFrame is a 2-dimensional labeled data structure with columns of potentially different types.

In [22]:
np.random.seed(101)
rand_mat=np.random.randn(5,4)
rand_mat

array([[ 2.70684984,  0.62813271,  0.90796945,  0.50382575],
       [ 0.65111795, -0.31931804, -0.84807698,  0.60596535],
       [-2.01816824,  0.74012206,  0.52881349, -0.58900053],
       [ 0.18869531, -0.75887206, -0.93323722,  0.95505651],
       [ 0.19079432,  1.97875732,  2.60596728,  0.68350889]])

In [23]:
df=pd.DataFrame(data=rand_mat,index='A B C D E'.split(),columns='W X Y Z'.split())
dfOriginal=df.copy()
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [24]:
df['W'] # extract column

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

In [25]:
type(df['W']) # a column is just Series

pandas.core.series.Series

In [26]:
type(df)

pandas.core.frame.DataFrame

In [27]:
df[['W','X']] # select columns from df

W         X
A  2.706850  0.628133
B  0.651118 -0.319318
C -2.018168  0.740122
D  0.188695 -0.758872
E  0.190794  1.978757

In [28]:
df['NEW']=df['W'] + df['X'] # add new column
df

W         X         Y         Z       NEW
A  2.706850  0.628133  0.907969  0.503826  3.334983
B  0.651118 -0.319318 -0.848077  0.605965  0.331800
C -2.018168  0.740122  0.528813 -0.589001 -1.278046
D  0.188695 -0.758872 -0.933237  0.955057 -0.570177
E  0.190794  1.978757  2.605967  0.683509  2.169552

In [29]:
df1=df.drop('NEW',axis=1) # delete column
df1

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [30]:
df.drop('NEW',axis=1,inplace=True) # delete column in the original df
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [31]:
df.drop('A',axis=0) # delete row do not change the original df

W         X         Y         Z
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [32]:
df.loc['A'] # extract row

W    2.706850
X    0.628133
Y    0.907969
Z    0.503826
Name: A, dtype: float64

In [33]:
df.iloc[0,2] # access the element of df

0.9079694464765431

In [34]:
df.loc[['A','B']][['W','X']] # select a part of df

W         X
A  2.706850  0.628133
B  0.651118 -0.319318

In [35]:
df.iloc[[0,1],[0,1]] # select a part of df using raw indices

W         X
A  2.706850  0.628133
B  0.651118 -0.319318

In [36]:
df.iloc[0:2,0:2] # select a contiguous part of df

W         X
A  2.706850  0.628133
B  0.651118 -0.319318

### Logical operations on DataFrames

In [37]:
df_bool=df >0
df_bool

W      X      Y      Z
A   True   True   True   True
B   True  False  False   True
C  False   True   True  False
D   True  False  False   True
E   True   True   True   True

In [ ]:
df[df_bool]

In [38]:
cond1=df['W'] >0
cond2=df['Y'] >1
df[cond1 & cond2]

W         X         Y         Z
E  0.190794  1.978757  2.605967  0.683509

In [39]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

### Operations on indices

In [40]:
df.reset_index(inplace=True)

In [41]:
df

index         W         X         Y         Z
0     A  2.706850  0.628133  0.907969  0.503826
1     B  0.651118 -0.319318 -0.848077  0.605965
2     C -2.018168  0.740122  0.528813 -0.589001
3     D  0.188695 -0.758872 -0.933237  0.955057
4     E  0.190794  1.978757  2.605967  0.683509

In [42]:
df.drop('index',axis=1,inplace=True)
df

W         X         Y         Z
0  2.706850  0.628133  0.907969  0.503826
1  0.651118 -0.319318 -0.848077  0.605965
2 -2.018168  0.740122  0.528813 -0.589001
3  0.188695 -0.758872 -0.933237  0.955057
4  0.190794  1.978757  2.605967  0.683509

In [43]:
df['States']='CA NY WY OR CO'.split()
df

W         X         Y         Z States
0  2.706850  0.628133  0.907969  0.503826     CA
1  0.651118 -0.319318 -0.848077  0.605965     NY
2 -2.018168  0.740122  0.528813 -0.589001     WY
3  0.188695 -0.758872 -0.933237  0.955057     OR
4  0.190794  1.978757  2.605967  0.683509     CO

In [44]:
df.set_index('States',inplace=True)
df

W         X         Y         Z
States                                        
CA      2.706850  0.628133  0.907969  0.503826
NY      0.651118 -0.319318 -0.848077  0.605965
WY     -2.018168  0.740122  0.528813 -0.589001
OR      0.188695 -0.758872 -0.933237  0.955057
CO      0.190794  1.978757  2.605967  0.683509

### Useful functions

In [45]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, CA to CO
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   W       5 non-null      float64
 1   X       5 non-null      float64
 2   Y       5 non-null      float64
 3   Z       5 non-null      float64
dtypes: float64(4)
memory usage: 200.0+ bytes


In [46]:
df.describe()

W         X         Y         Z
count  5.000000  5.000000  5.000000  5.000000
mean   0.343858  0.453764  0.452287  0.431871
std    1.681131  1.061385  1.454516  0.594708
min   -2.018168 -0.758872 -0.933237 -0.589001
25%    0.188695 -0.319318 -0.848077  0.503826
50%    0.190794  0.628133  0.528813  0.605965
75%    0.651118  0.740122  0.907969  0.683509
max    2.706850  1.978757  2.605967  0.955057

### Nan handling

In [47]:
df=pd.DataFrame({'A' : [1,2,np.nan], 'B' : [5, np.nan, np.nan], 'C' : [1,2,3]})
df

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [48]:
df.dropna() # drop all rows with nans

A    B  C
0  1.0  5.0  1

In [49]:
df.dropna(axis=1) # drop all columns with  nans

C
0  1
1  2
2  3

In [50]:
df.dropna(thresh=2) # drop all rows with two or more nans

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2

In [ ]:
df

In [51]:
df.mean()

A    1.5
B    5.0
C    2.0
dtype: float64

In [52]:
df.fillna(value='FILL VALUE') # replace nans by string

A           B  C
0         1.0         5.0  1
1         2.0  FILL VALUE  2
2  FILL VALUE  FILL VALUE  3

In [53]:
df.fillna(0) # replace nan by zero

A    B  C
0  1.0  5.0  1
1  2.0  0.0  2
2  0.0  0.0  3

In [ ]:
df.fillna()

In [54]:
df

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

### Miscellaneous

In [55]:
data={'Company' :['GOOG','GOOG','MSFT','MSFT','FB','FB'],
      'Person' : ['Sam','Charlie','Amy','Eve','Carl','Sarah'],
      'Sales' :[200,120,340,600,243,350]}
data

{'Company': ['GOOG', 'GOOG', 'MSFT', 'MSFT', 'FB', 'FB'],
 'Person': ['Sam', 'Charlie', 'Amy', 'Eve', 'Carl', 'Sarah'],
 'Sales': [200, 120, 340, 600, 243, 350]}

In [56]:
df=pd.DataFrame(data)
df

Company   Person  Sales
0    GOOG      Sam    200
1    GOOG  Charlie    120
2    MSFT      Amy    340
3    MSFT      Eve    600
4      FB     Carl    243
5      FB    Sarah    350

In [57]:
df.groupby('Company').mean()

Sales
Company       
FB       296.5
GOOG     160.0
MSFT     470.0

In [58]:
df.groupby('Company').describe()

Sales                                                        
        count   mean         std    min     25%    50%     75%    max
Company                                                              
FB        2.0  296.5   75.660426  243.0  269.75  296.5  323.25  350.0
GOOG      2.0  160.0   56.568542  120.0  140.00  160.0  180.00  200.0
MSFT      2.0  470.0  183.847763  340.0  405.00  470.0  535.00  600.0

In [59]:
df.groupby('Company').describe().transpose()

Company              FB        GOOG        MSFT
Sales count    2.000000    2.000000    2.000000
      mean   296.500000  160.000000  470.000000
      std     75.660426   56.568542  183.847763
      min    243.000000  120.000000  340.000000
      25%    269.750000  140.000000  405.000000
      50%    296.500000  160.000000  470.000000
      75%    323.250000  180.000000  535.000000
      max    350.000000  200.000000  600.000000

In [60]:
df=pd.DataFrame({'col1' : [1,2,3,4], 'col2': [444,555,666,444],'col3' : ['abs','def','ghi','xyz']})
df

col1  col2 col3
0     1   444  abs
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [61]:
df['col2'].unique() # get a list of unique values in a column

array([444, 555, 666])

In [62]:
df['col2'].nunique() # a number of unique values

3

In [64]:
df['col2'].value_counts() #distinct value count

444    2
555    1
666    1
Name: col2, dtype: int64

In [66]:
def times_two(number):
    return 2*number

In [67]:
times_two(4)

8

In [68]:
df['new']=df['col1'].apply(times_two) # apply fuction to a column
df

col1  col2 col3  new
0     1   444  abs    2
1     2   555  def    4
2     3   666  ghi    6
3     4   444  xyz    8

In [69]:
df.sort_values('col2') # sorting example

col1  col2 col3  new
0     1   444  abs    2
3     4   444  xyz    8
1     2   555  def    4
2     3   666  ghi    6

In [70]:
df.sort_values('col2',ascending=False)

col1  col2 col3  new
2     3   666  ghi    6
1     2   555  def    4
0     1   444  abs    2
3     4   444  xyz    8